# Generated by Django 5.0 on 2024-03-28 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluador',
            name='codigo_evaluador',
            field=models.CharField(default=datetime.datetime(2024, 3, 28, 14, 44, 31, 199938, tzinfo=datetime.timezone.utc), max_length=8),
            preserve_default=False,
        ),
    ]
