# Generated by Django 5.0 on 2024-03-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0002_evaluador_codigo_evaluador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluador',
            name='codigo_evaluador',
            field=models.CharField(max_length=6),
        ),
    ]
