# Generated by Django 5.0 on 2024-03-28 17:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0003_alter_evaluador_codigo_evaluador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('idPostulante', models.AutoField(primary_key=True, serialize=False)),
                ('ap_paterno', models.CharField(max_length=100)),
                ('ap_materno', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('pdf_curriculum', models.FileField(upload_to='curriculum')),
                ('id_programa', models.IntegerField()),
                ('id_doctorado', models.IntegerField()),
                ('id_mencion', models.IntegerField()),
                ('id_maestria', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='evaluador',
            name='codigo_evaluador',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('idEvaluador', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(editable=False, max_length=10, unique=True)),
                ('fecha_creacion', models.DateField(default=datetime.datetime(2024, 3, 28, 12, 23, 15, 969576))),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.evaluador')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.postulante')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEvaluacion',
            fields=[
                ('idDetalleEva', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje_promedioP', models.FloatField(blank=True, null=True)),
                ('puntaje_cursosEva', models.FloatField(blank=True, null=True)),
                ('puntaje_partCientifica', models.FloatField(blank=True, null=True)),
                ('puntaje_docenciaUni', models.FloatField(blank=True, null=True)),
                ('puntaje_idiomaExt', models.FloatField(blank=True, null=True)),
                ('puntaje_capacitacion', models.FloatField(blank=True, null=True)),
                ('puntaje_libroInscritos', models.FloatField(blank=True, null=True)),
                ('puntaje_publicaciones', models.FloatField(blank=True, null=True)),
                ('puntaje_proyInvestig', models.FloatField(blank=True, null=True)),
                ('puntaje_asesoriaProy', models.FloatField(blank=True, null=True)),
                ('puntaje_produccionCien', models.FloatField(blank=True, null=True)),
                ('puntajeFinal', models.FloatField(blank=True, null=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.evaluacion')),
            ],
        ),
    ]
