# Generated by Django 5.0 on 2024-03-28 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0004_postulante_alter_evaluador_codigo_evaluador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2024, 3, 28, 18, 20, 29, 348359)),
        ),
    ]
