# Generated by Django 5.0 on 2024-03-28 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0005_alter_evaluacion_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2024, 3, 28, 18, 24, 43, 380394)),
        ),
        migrations.AlterField(
            model_name='evaluador',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='id_doctorado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='id_maestria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='id_mencion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='id_programa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='pdf_curriculum',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
