# Generated by Django 5.0 on 2024-03-28 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0006_alter_evaluacion_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='codigo',
            new_name='codigo_evaluacion',
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2024, 3, 28, 18, 42, 58, 41250)),
        ),
    ]
