# Generated by Django 5.0 on 2024-03-29 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0008_alter_evaluacion_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='codigo_evaluacion',
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2024, 3, 28, 22, 45, 44, 816918)),
        ),
    ]
