# Generated by Django 5.0 on 2024-03-29 03:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0009_alter_evaluacion_codigo_evaluacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2024, 3, 28, 22, 48, 26, 477090)),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='postulante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.postulante', unique=True),
        ),
    ]
