# Generated by Django 5.0 on 2024-03-30 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0011_alter_evaluacion_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='idEvaluador',
            new_name='idEvaluacion',
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
