# Generated by Django 5.0 on 2024-03-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0012_rename_idevaluador_evaluacion_idevaluacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='codigo_evaluacion',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
