# Generated by Django 5.0 on 2024-03-31 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0013_alter_evaluacion_codigo_evaluacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntajeFinal',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(35.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_asesoriaProy',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(0.75)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_capacitacion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(24.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_cursosEva',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_docenciaUni',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_idiomaExt',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_libroInscritos',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_partCientifica',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_produccionCien',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(11.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_promedioP',
            field=models.FloatField(blank=True, default=6.0, null=True, validators=[django.core.validators.MaxValueValidator(12.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_proyInvestig',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(0.5)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_publicaciones',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3.0)]),
        ),
    ]
