# Generated by Django 5.0 on 2024-04-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0014_alter_detalleevaluacion_puntajefinal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='codigo_evaluacion',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
