# Generated by Django 5.0 on 2024-04-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0015_alter_evaluacion_codigo_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='codigo_evaluacion',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
