# Generated by Django 5.0 on 2024-04-03 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0016_alter_evaluacion_codigo_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='estado_evaluacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntajeFinal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(35.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_asesoriaProy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_capacitacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(24.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_cursosEva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_docenciaUni',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(3.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_idiomaExt',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_libroInscritos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_partCientifica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_produccionCien',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(11.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_promedioP',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=5, validators=[django.core.validators.MinValueValidator(6.0), django.core.validators.MaxValueValidator(12.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_proyInvestig',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='detalleevaluacion',
            name='puntaje_publicaciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)]),
        ),
    ]
