# Generated by Django 5.0 on 2024-04-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0018_alter_detalleevaluacion_evaluacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='estado_evaluacion',
            field=models.BooleanField(default=False),
        ),
    ]
