# Generated by Django 5.0 on 2024-04-04 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0019_alter_evaluacion_estado_evaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorado',
            fields=[
                ('idDoctorado', models.AutoField(primary_key=True, serialize=False)),
                ('des_doctorado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maestria',
            fields=[
                ('idMaestria', models.AutoField(primary_key=True, serialize=False)),
                ('des_maestria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('idModalidad', models.AutoField(primary_key=True, serialize=False)),
                ('des_modalidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='id_mencion',
        ),
        migrations.AlterField(
            model_name='postulante',
            name='id_doctorado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.doctorado'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='id_maestria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.maestria'),
        ),
        migrations.AddField(
            model_name='maestria',
            name='mod_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.modalidad'),
        ),
        migrations.AddField(
            model_name='doctorado',
            name='mod_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.modalidad'),
        ),
    ]
