# Generated by Django 5.0 on 2024-04-05 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0020_doctorado_maestria_modalidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulante',
            old_name='telefono',
            new_name='celular',
        ),
        migrations.RemoveField(
            model_name='doctorado',
            name='mod_estado',
        ),
        migrations.RemoveField(
            model_name='maestria',
            name='mod_estado',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='id_programa',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='sexo',
        ),
        migrations.AddField(
            model_name='postulante',
            name='id_modalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.modalidad'),
        ),
    ]
