# Generated by Django 5.0 on 2024-04-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0021_rename_telefono_postulante_celular_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulante',
            old_name='id_doctorado',
            new_name='doctorado',
        ),
        migrations.RenameField(
            model_name='postulante',
            old_name='id_maestria',
            new_name='maestria',
        ),
        migrations.RenameField(
            model_name='postulante',
            old_name='id_modalidad',
            new_name='modalidad',
        ),
    ]
