# Generated by Django 5.0 on 2024-04-05 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0022_rename_id_doctorado_postulante_doctorado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('idUnidad', models.AutoField(primary_key=True, serialize=False)),
                ('des_unidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='postulante',
            name='unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appevaluacion.unidad'),
        ),
    ]
