# Generated by Django 5.0 on 2024-04-05 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0024_alter_postulante_doctorado_alter_postulante_maestria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulante',
            name='fecha_nacimiento',
        ),
    ]
