# Generated by Django 5.0 on 2024-04-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0025_remove_postulante_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='dni',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
