# Generated by Django 5.0 on 2024-04-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0026_alter_postulante_celular_alter_postulante_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
