# Generated by Django 5.0 on 2024-04-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0028_remove_evaluador_direccion_remove_evaluador_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluador',
            name='sexo',
        ),
        migrations.AlterField(
            model_name='evaluador',
            name='dni',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='evaluador',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
