# Generated by Django 5.0 on 2024-04-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appevaluacion', '0029_remove_evaluador_sexo_alter_evaluador_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluador',
            name='dni',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
